### ISSUE TITLE
Paper results replication failed (fixed)

### ISSUE THREAD

**Issue by zerjioang** [SeUniVr/EtherSolve#6]
Im trying to replicate the results described in your paper (https://arxiv.org/abs/2103.09113) in where according to results section, the ethersolve tool is capable of having a success rate of 997/1000 using provided Benchmarking dataset. I replicated the experiment setting a 10 minute timeout using the dataset (https://github.com/SeUniVr/EtherSolve_ICPC2021_ReplicationPackage) at commit `9253ff2`, and I was not able to get the same results. This is what I get:

## Summary

```bash
TIMEOUT: 7
ERRORED: 40
SUCCESS: 953

current accuracy: 953/1000 = 95,3 %
```

### Command line

The command I'm running is:

```bash
java -jar ./EtherSolve.jar --runtime --json --re-entrancy ${sample_file}
```

### Execution Log

See the execution log attached.
[execution_log.txt](https://github.com/SeUniVr/EtherSolve/files/10331483/execution_log.txt)

```bash
Execution result:

TIMEOUT: 7
ERRORED: 40
SUCCESS: 953

current accuracy: 953/1000 = 95,3 %
```
</details>

As you can see, there are many samples that fail when analyzed (either by timeout or error). Considering that many of those samples create a runtime error in the Java application, I see it impossible to get such a success rate. 

#### timeout list

```bash
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x0000000000ab32e9e7bd6bd3c37a7e99fb8c2d43.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x371128cd849cee2e4b10f1883319e66ebf2c70b9.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x55d568af5cee6a69898b280b691b7e91c31f9fff.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x5cb2f04e6a63f38624cfca70955eaf5f215b8f4d.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x96569f124f6a3b62093c7115f14f8005705ba48a.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xb5371de91bde1dc3640219887ea03510a4a2701b.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xe3b42413186f3d91e4e7e20a4dfdabb207595405.evm
```

#### errored list

```bash
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x02114334e7ff9601085d5b5805f8694147317c3f.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x054bfcd07b64575c23c0045615b37b297e2e2929.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x06a18723818cdf9ab08ed8ceb0b931777a41c8f9.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x0ca0d1d286bcd99d8c48b3ac71269b793b45dab3.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x0d8fc15b6fefc278ff642861df51b45607330871.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x0de2a05c8a3f25651c7fe0fdad821aeec916f7fa.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x13110480c3c83ad103159ca239d82feb7a9b1a45.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x24d6193066d21d36938dc336322c64034af202d9.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x28ad54a7208608d17b8d4a4a4034f254a28df85e.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x2d2b7929731c926f8ce373a78863080e9ad53356.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x2da6482c770c55b23f66a6190e8bb76862419aaf.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x351db37eb42e335a5007d3e6ac1afabb66d944c5.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x3a415765dB8bDA5F97583eA212FDc2ab5e939F0C.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x407cf8ec38ce84145ada916a41e6623c769551b6.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x41d6d16524b0fa908324230946bdf44dd68a61ed.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x424c9035bc3606f2887a5bbe28beaa9de49db9e8.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x4673D0270D05260d39F6FdAF31D620Be95d242AB.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x47b2223eb33ba465abd6d4f9f2883c0932bc4b20.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x59a413b0dc16a6be63b351bf4dec73faa6850bff.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x5d63846de87179ebfed8b9c512d503c07516d94d.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x60c409d9135aae95d53b44fef6adf371db9260fb.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x62ae810c2209702c1b1725c44107c413c1ab8231.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x635c47ab07b9d6fc3a52f705d494e7c30c0323d2.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x670577feb18576c10f632b2e26976e659d1e5e33.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x6736077ae034e16f7fafd2d5ed1358370fda1f88.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x786a105d6b23592a4a16c19e8785c5689db7c926.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x882bd868495323dd7d903e2ad69ef0b1f7d8853e.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xb7f4c286851cbf0cbf2fe8ebf40412b196c0e8ad.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xbe88621ac812204645d8b71fde134949113f0f2f.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xc6c8bce5e9383df025f982d6bbd84163957a6979.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xc6e5e9c6f4f3d1667df6086e91637cc7c64a13eb.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xc8af9acb3d9b8827e863d416f740c7e97eb5a72f.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xc924bcd807c57b06da8755039d953d3bdfb573a2.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xcf369852f4149421f94b31a2530761da8bd9a870.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xd917635caf144e6ebbbdfd7e6725c563db756079.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xe37d27660E5B8B861641b9D52009344f20534084.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xe393ef6fa3bbfc7e72a05bfd12ce88be5c7e46f0.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xee0f286776639cd363da810daf3e0623f82576b0.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xfa8ff51e0c67600b9abe5c89b53cc36ee6c7bf76.evm
EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0xfd77ee88f5678553a575b7302c48e9aba9597d8c.evm
```

An example of such error is:

```bash
java -jar ./EtherSolve.jar --runtime --json --re-entrancy ./EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x28ad54a7208608d17b8d4a4a4034f254a28df85e.evm

java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at parseTree.SymbolicExecution.SymbolicExecutionStack.peek(SymbolicExecutionStack.java:89)
	at analysers.StoreAccessAfterUnsafeCall.isUnsafeCall(StoreAccessAfterUnsafeCall.java:74)
	at analysers.StoreAccessAfterUnsafeCall.analyse(StoreAccessAfterUnsafeCall.java:33)
	at cli.MainCLI.runReEntrancyDetector(MainCLI.java:173)
	at cli.MainCLI.call(MainCLI.java:84)
	at cli.MainCLI.call(MainCLI.java:24)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at cli.MainCLI.main(MainCLI.java:102)
```

## Used Version

To check the actual `ethersolve` version, I use the command:

```bash
java -jar ./EtherSolve.jar -V
1.0
```

Note that current `.jar` files is downloaded from `https://github.com/SeUniVr/EtherSolve_ICPC2021_ReplicationPackage/blob/master/EtherSolve.jar`

## What I expect

I was expecting to have the same results described in the paper. Any advice or updated version of the tool is welcome. Thanks

**Comment by VersusF** [comment]
Hello,
the bytecode downloaded from the verified contracts in Etherscan is creation-code, not runtime-code. Did you try the analysis with the `--creation` flag instead of the `--runtime`?

**Comment by zerjioang** [comment]
@VersusF I think I'm using the right flag. 

Take for example the following contract case from the mentioned 'replication package'. I think all contracts in that package are runtime contracts because construction data is missing. Take for example the sample contract:

* https://github.com/SeUniVr/EtherSolve_ICPC2021_ReplicationPackage/blob/master/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x00000000938f41360a846490409500d08919856c.evm

## Contract bytecode

```bash
608060405234801561001057600080fd5b50600436106101c45760003560e01c80638da5cb5b116100f9578063c49c2eb611610097578063dd62ed3e11610071578063dd62ed3e14610564578063e808386314610592578063e918ad91146105af578063f2fde38b146105cc576101c4565b8063c49c2eb6146104a9578063cf44b5d5146104b1578063da4e364f14610509576101c4565b8063a457c2d7116100d3578063a457c2d714610441578063a9059cbb1461046d578063b2a8c6fe14610499578063bafebc6f146104a1576101c4565b80638da5cb5b1461040d5780638f32d59b1461043157806395d89b4114610439576101c4565b80633d8b7894116101665780636aa633b6116101405780636aa633b6146103a157806370a08231146103a957806379ba5097146103cf5780638a539972146103d7576101c4565b80633d8b78941461032a5780633f1fc678146103475780634e69d56014610375576101c4565b806323452b9c116101a257806323452b9c146102a057806323b872dd146102aa578063313ce567146102e057806339509351146102fe576101c4565b806306fdde03146101c9578063095ea7b31461024657806318160ddd14610286575b600080fd5b6101d16105f2565b6040805160208082528351818301528351919283929083019185019080838360005b8381101561020b5781810151838201526020016101f3565b50505050905090810190601f1680156102385780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b6102726004803603604081101561025c57600080fd5b506001600160a01b038135169060200135610629565b604080519115158252519081900360200190f35b61028e610640565b60408051918252519081900360200190f35b6102a8610646565b005b610272600480360360608110156102c057600080fd5b506001600160a01b0381358116916020810135909116906040013561069b565b6102e86106f2565b6040805160ff9092168252519081900360200190f35b6102726004803603604081101561031457600080fd5b506001600160a01b0381351690602001356106f7565b61028e6004803603602081101561034057600080fd5b5035610733565b61034f61091e565b604080519485526020850193909352838301919091526060830152519081900360800190f35b61037d610b1c565b6040518082600281111561038d57fe5b60ff16815260200191505060405180910390f35b610272610b25565b61028e600480360360208110156103bf57600080fd5b50356001600160a01b0316610bb6565b6102a8610bd1565b6103f4600480360360208110156103ed57600080fd5b5035610c76565b6040805192835260208301919091528051918290030190f35b61041561103b565b604080516001600160a01b039092168252519081900360200190f35b61027261104a565b6101d161105b565b6102726004803603604081101561045757600080fd5b506001600160a01b03813516906020013561107e565b6102726004803603604081101561048357600080fd5b506001600160a01b0381351690602001356110ba565b6102a86110c7565b610415611119565b61028e611131565b6104b96111b1565b60408051602080825283518183015283519192839290830191858101910280838360005b838110156104f55781810151838201526020016104dd565b505050509050019250505060405180910390f35b6105266004803603602081101561051f57600080fd5b50356111bd565b6040805195865260208601949094526001600160a01b039092168484015265ffffffffffff9081166060850152166080830152519081900360a00190f35b61028e6004803603604081101561057a57600080fd5b506001600160a01b0381358116916020013516611270565b6102a8600480360360208110156105a857600080fd5b503561129b565b6102a8600480360360208110156105c557600080fd5b503561136e565b6102a8600480360360208110156105e257600080fd5b50356001600160a01b03166114c8565b60408051808201909152601d81527f446169204261636b73746f702053796e6469636174652076312d313030000000602082015290565b6000610636338484611572565b5060015b92915050565b60045490565b61064e61104a565b6106895760405162461bcd60e51b81526004018080602001828103825260288152602001806120276028913960400191505060405180910390fd5b600180546001600160a01b0319169055565b60006106a884848461165e565b6001600160a01b0384166000908152600360209081526040808320338085529252909120546106e89186916106e3908663ffffffff6117a216565b611572565b5060019392505050565b601290565b3360008181526003602090815260408083206001600160a01b038716845290915281205490916106369185906106e3908663ffffffff6117ff16565b6000600260055460ff16600281111561074857fe5b14156107855760405162461bcd60e51b8152600401808060200182810382526053815260200180611eb76053913960600191505060405180910390fd5b600060055460ff16600281111561079857fe5b146107d45760405162461bcd60e51b8152600401808060200182810382526055815260200180611f8d6055913960600191505060405180910390fd5b604080516323b872dd60e01b8152336004820152306024820152604481018490529051736b175474e89094c44da98b954eedeac495271d0f916323b872dd9160648083019260209291908290030181600087803b15801561083457600080fd5b505af1158015610848573d6000803e3d6000fd5b505050506040513d602081101561085e57600080fd5b505161089b5760405162461bcd60e51b8152600401808060200182810382526047815260200180611f0a6047913960600191505060405180910390fd5b60408051633b4da69f60e01b8152306004820152602481018490529051739759a6ac90977b93b58547b4a71c78317f391a2891633b4da69f91604480830192600092919082900301818387803b1580156108f457600080fd5b505af1158015610908573d6000803e3d6000fd5b505050508190506109193382611860565b919050565b600080600080734d95a049d5b0b7d32058cd3f2163015747522e996001600160a01b0316637d780d826040518163ffffffff1660e01b815260040160206040518083038186803b15801561097157600080fd5b505afa158015610985573d6000803e3d6000fd5b505050506040513d602081101561099b57600080fd5b5051604080516324d8499b60e21b81529051734d95a049d5b0b7d32058cd3f2163015747522e9991639361266c916004808301926020929190829003018186803b1580156109e857600080fd5b505afa1580156109fc573d6000803e3d6000fd5b505050506040513d6020811015610a1257600080fd5b505160408051634e8b1dd560e01b81529051734d95a049d5b0b7d32058cd3f2163015747522e9991634e8b1dd5916004808301926020929190829003018186803b158015610a5f57600080fd5b505afa158015610a73573d6000803e3d6000fd5b505050506040513d6020811015610a8957600080fd5b50516040805163cfc4af5560e01b81529051734d95a049d5b0b7d32058cd3f2163015747522e999163cfc4af55916004808301926020929190829003018186803b158015610ad657600080fd5b505afa158015610aea573d6000803e3d6000fd5b505050506040513d6020811015610b0057600080fd5b5051929791965065ffffffffffff908116955090911692509050565b60055460ff1690565b6000734d95a049d5b0b7d32058cd3f2163015747522e996001600160a01b031663957aa58c6040518163ffffffff1660e01b815260040160206040518083038186803b158015610b7457600080fd5b505afa158015610b88573d6000803e3d6000fd5b505050506040513d6020811015610b9e57600080fd5b5051600114610bae576000610bb1565b60015b905090565b6001600160a01b031660009081526002602052604090205490565b6001546001600160a01b03163314610c1a5760405162461bcd60e51b8152600401808060200182810382526045815260200180611fe26045913960600191505060405180910390fd5b600180546001600160a01b03191690556000805460405133926001600160a01b03909216917f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e091a3600080546001600160a01b03191633179055565b6000806000610caa610c86610640565b610c9e86670de0b6b3a764000063ffffffff61195216565b9063ffffffff6119ab16565b9050610cb63385611a15565b6000610cc0611af0565b60408051633612d9a360e11b815230600482015290519192506000917335d1b3f3d7966a1dfe207aa4514c12a259a0492b91636c25b346916024808301926020929190829003018186803b158015610d1757600080fd5b505afa158015610d2b573d6000803e3d6000fd5b505050506040513d6020811015610d4157600080fd5b505190506000610d57838363ffffffff6117ff16565b604080516370a0823160e01b81523060048201529051919250600091739f8f72aa9304c8b593d555f12ef6589cc3a579a2916370a08231916024808301926020929190829003018186803b158015610dae57600080fd5b505afa158015610dc2573d6000803e3d6000fd5b505050506040513d6020811015610dd857600080fd5b505190506000670de0b6b3a7640000610df7848863ffffffff61195216565b81610dfe57fe5b049050670de0b6b3a7640000610e1a838863ffffffff61195216565b81610e2157fe5b0496506b033b2e3c9fd0803ce80000008104975083811115610e745760405162461bcd60e51b8152600401808060200182810382526042815260200180611e206042913960600191505060405180910390fd5b610e7c610b25565b15610ef7576040805163ef693bed60e01b8152336004820152602481018a90529051739759a6ac90977b93b58547b4a71c78317f391a289163ef693bed91604480830192600092919082900301818387803b158015610eda57600080fd5b505af1158015610eee573d6000803e3d6000fd5b50505050610f6f565b6040805163bb35783b60e01b81523060048201523360248201526044810183905290517335d1b3f3d7966a1dfe207aa4514c12a259a0492b9163bb35783b91606480830192600092919082900301818387803b158015610f5657600080fd5b505af1158015610f6a573d6000803e3d6000fd5b505050505b6040805163a9059cbb60e01b8152336004820152602481018990529051739f8f72aa9304c8b593d555f12ef6589cc3a579a29163a9059cbb9160448083019260209291908290030181600087803b158015610fc957600080fd5b505af1158015610fdd573d6000803e3d6000fd5b505050506040513d6020811015610ff357600080fd5b50516110305760405162461bcd60e51b8152600401808060200182810382526033815260200180611e846033913960400191505060405180910390fd5b505050505050915091565b6000546001600160a01b031690565b6000546001600160a01b0316331490565b604080518082019091526009815268044425376312d3130360bc1b602082015290565b3360008181526003602090815260408083206001600160a01b038716845290915281205490916106369185906106e3908663ffffffff6117a216565b600061063633848461165e565b6110cf61104a565b61110a5760405162461bcd60e51b81526004018080602001828103825260288152602001806120276028913960400191505060405180910390fd5b6005805460ff19166002179055565b734d95a049d5b0b7d32058cd3f2163015747522e9990565b6000734d95a049d5b0b7d32058cd3f2163015747522e996001600160a01b031663cfdd33026040518163ffffffff1660e01b815260040160206040518083038186803b15801561118057600080fd5b505afa158015611194573d6000803e3d6000fd5b505050506040513d60208110156111aa57600080fd5b5051905090565b6060610bb16006611b64565b6000806000806000734d95a049d5b0b7d32058cd3f2163015747522e996001600160a01b0316634423c5f1876040518263ffffffff1660e01b81526004018082815260200191505060a06040518083038186803b15801561121d57600080fd5b505afa158015611231573d6000803e3d6000fd5b505050506040513d60a081101561124757600080fd5b508051602082015160408301516060840151608090940151929a91995097509195509350915050565b6001600160a01b03918216600090815260036020908152604080832093909416825291909152205490565b6112ac60068263ffffffff611bea16565b6112e75760405162461bcd60e51b815260040180806020018281038252603c815260200180611f51603c913960400191505060405180910390fd5b6000806112f3836111bd565b945050935050508065ffffffffffff16600014611324576001600160a01b0382163014156113245761132483611bff565b61133560068463ffffffff611c7416565b506040805184815290517f2d7633a748a750b559b97738629efd586b561319b152bb42ba14d590706d31da9181900360200190a1505050565b600260055460ff16600281111561138157fe5b14156113be5760405162461bcd60e51b8152600401808060200182810382526053815260200180611eb76053913960600191505060405180910390fd5b6113cf60068263ffffffff611bea16565b1561140b5760405162461bcd60e51b815260040180806020018281038252603a815260200180612070603a913960400191505060405180910390fd5b6000611416826111bd565b505050509050600060646b033b2e3c9fd0803ce8000000838161143557fe5b048161143d57fe5b04905061144b838284611d3d565b600160055460ff16600281111561145e57fe5b14611471576005805460ff191660011790555b61148260068463ffffffff611dbb16565b50604080518481526020810183905280820184905290517f35f50010a71a711fbfb0ada2814c5caf05bf153ccea88acca671ab6a5615d7c79181900360600190a1505050565b6114d061104a565b61150b5760405162461bcd60e51b81526004018080602001828103825260288152602001806120276028913960400191505060405180910390fd5b6001600160a01b0381166115505760405162461bcd60e51b81526004018080602001828103825260388152602001806121146038913960400191505060405180910390fd5b600180546001600160a01b0319166001600160a01b0392909216919091179055565b6001600160a01b0383166115b75760405162461bcd60e51b81526004018080602001828103825260248152602001806120f06024913960400191505060405180910390fd5b6001600160a01b0382166115fc5760405162461bcd60e51b8152600401808060200182810382526022815260200180611e626022913960400191505060405180910390fd5b6001600160a01b03808416600081815260036020908152604080832094871680845294825291829020859055815185815291517f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b9259281900390910190a3505050565b6001600160a01b0383166116a35760405162461bcd60e51b81526004018080602001828103825260258152602001806120cb6025913960400191505060405180910390fd5b6001600160a01b0382166116e85760405162461bcd60e51b8152600401808060200182810382526023815260200180611dfd6023913960400191505060405180910390fd5b6001600160a01b038316600090815260026020526040902054611711908263ffffffff6117a216565b6001600160a01b038085166000908152600260205260408082209390935590841681522054611746908263ffffffff6117ff16565b6001600160a01b0380841660008181526002602090815260409182902094909455805185815290519193928716927fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef92918290030190a3505050565b6000828211156117f9576040805162461bcd60e51b815260206004820152601e60248201527f536166654d6174683a207375627472616374696f6e206f766572666c6f770000604482015290519081900360640190fd5b50900390565b600082820183811015611859576040805162461bcd60e51b815260206004820152601b60248201527f536166654d6174683a206164646974696f6e206f766572666c6f770000000000604482015290519081900360640190fd5b9392505050565b6001600160a01b0382166118bb576040805162461bcd60e51b815260206004820152601f60248201527f45524332303a206d696e7420746f20746865207a65726f206164647265737300604482015290519081900360640190fd5b6004546118ce908263ffffffff6117ff16565b6004556001600160a01b0382166000908152600260205260409020546118fa908263ffffffff6117ff16565b6001600160a01b03831660008181526002602090815260408083209490945583518581529351929391927fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef9281900390910190a35050565b6000826119615750600061063a565b8282028284828161196e57fe5b04146118595760405162461bcd60e51b815260040180806020018281038252602181526020018061204f6021913960400191505060405180910390fd5b6000808211611a01576040805162461bcd60e51b815260206004820152601a60248201527f536166654d6174683a206469766973696f6e206279207a65726f000000000000604482015290519081900360640190fd5b6000828481611a0c57fe5b04949350505050565b6001600160a01b038216611a5a5760405162461bcd60e51b81526004018080602001828103825260218152602001806120aa6021913960400191505060405180910390fd5b600454611a6d908263ffffffff6117a216565b6004556001600160a01b038216600090815260026020526040902054611a99908263ffffffff6117a216565b6001600160a01b0383166000818152600260209081526040808320949094558351858152935191937fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef929081900390910190a35050565b60006060611afe6006611b64565b9050600080805b8351811015611b5d57611b2a848281518110611b1d57fe5b60200260200101516111bd565b50929550935050506001600160a01b038216301415611b5557611b53858463ffffffff6117ff16565b505b600101611b05565b5050505090565b6060808260010180549050604051908082528060200260200182016040528015611b98578160200160208202803883390190505b50905060005b6001840154811015611be357836001018181548110611bb957fe5b9060005260206000200154828281518110611bd057fe5b6020908102919091010152600101611b9e565b5092915050565b60009081526020919091526040902054151590565b734d95a049d5b0b7d32058cd3f2163015747522e996001600160a01b031663c959c42b826040518263ffffffff1660e01b815260040180828152602001915050600060405180830381600087803b158015611c5957600080fd5b505af1158015611c6d573d6000803e3d6000fd5b5050505050565b6000611c808383611bea565b15611d355760008281526020849052604090205460018401546000199182019101808214611cf8576000856001018281548110611cb957fe5b9060005260206000200154905080866001018481548110611cd657fe5b6000918252602080832090910192909255918252869052604090206001830190555b60008481526020869052604081205560018501805480611d1457fe5b6001900381819060005260206000200160009055905560019250505061063a565b50600061063a565b60408051632ff9d1c160e11b81526004810185905260248101849052604481018390529051734d95a049d5b0b7d32058cd3f2163015747522e9991635ff3a38291606480830192600092919082900301818387803b158015611d9e57600080fd5b505af1158015611db2573d6000803e3d6000fd5b50505050505050565b6000611dc78383611bea565b611d3557506001808301805480830182556000828152602080822090920185905591548483529085905260409091205561063a56fe45524332303a207472616e7366657220746f20746865207a65726f20616464726573734461694261636b73746f7053796e6469636174652f6465666563743a20496e73756666696369656e74204461692028696e2075736520696e2061756374696f6e732945524332303a20617070726f766520746f20746865207a65726f20616464726573734461694261636b73746f7053796e6469636174652f6465666563743a204d4b5220726564656d7074696f6e206661696c65642e4461694261636b73746f7053796e6469636174652f6e6f745768656e44656163746976617465643a2053796e6469636174652069732064656163746976617465642c20706c656173652077697468647261772e4461694261636b73746f7053796e6469636174652f656e6c6973743a20436f756c64206e6f74207472616e736665722044616920616d6f756e742066726f6d2063616c6c65722e4461694261636b73746f7053796e6469636174652f656e74657241756374696f6e3a2041756374696f6e20616c72656164792066696e616c697a65644461694261636b73746f7053796e6469636174652f656e6c6973743a2043616e6e6f74206465706f736974206f6e6365207468652066697273742061756374696f6e2062696420686173206265656e206d6164652e54776f537465704f776e61626c653a2063757272656e74206f776e6572206d757374207365742063616c6c6572206173206e657720706f74656e7469616c206f776e65722e54776f537465704f776e61626c653a2063616c6c6572206973206e6f7420746865206f776e65722e536166654d6174683a206d756c7469706c69636174696f6e206f766572666c6f774461694261636b73746f7053796e6469636174652f656e74657241756374696f6e3a2041756374696f6e20616c7265616479206163746976652e45524332303a206275726e2066726f6d20746865207a65726f206164647265737345524332303a207472616e736665722066726f6d20746865207a65726f206164647265737345524332303a20617070726f76652066726f6d20746865207a65726f206164647265737354776f537465704f776e61626c653a206e657720706f74656e7469616c206f776e657220697320746865207a65726f20616464726573732ea265627a7a723158200fb8f071da7a27144016c01fb53020833c773ab670aceb2786a25d69069cff4664736f6c63430005100032
```

If you download the same contract from Etherscan (https://etherscan.io/address/0x00000000938f41360a846490409500d08919856c#code) you can see that the constructor section is there defined as:

```bash
608060405234801561001057600080fd5b50600080546001600160a01b03191632178082556040516001600160a01b039190911691907f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0908290a36005805460ff19169055604080516328ec8bf160e21b8152739759a6ac90977b93b58547b4a71c78317f391a28600482015290517335d1b3f3d7966a1dfe207aa4514c12a259a0492b9163a3b22fc491602480830192600092919082900301818387803b1580156100ca57600080fd5b505af11580156100de573d6000803e3d6000fd5b50506040805163095ea7b360e01b8152739759a6ac90977b93b58547b4a71c78317f391a28600482015260001960248201529051736b175474e89094c44da98b954eedeac495271d0f935063095ea7b3925060448083019260209291908290030181600087803b15801561015157600080fd5b505af1158015610165573d6000803e3d6000fd5b505050506040513d602081101561017b57600080fd5b50506121808061018c6000396000f3fe
````

and that section is missing in  https://github.com/SeUniVr/EtherSolve_ICPC2021_ReplicationPackage/blob/master/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x00000000938f41360a846490409500d08919856c.evm

Thanks why Im using `--runtime` instead of `--creation`. So, whats the command I should use?

**Comment by VersusF** [comment]
Yes, you are right, the code type is runtime. Do you get the same result without the `--re-entrancy` flag? Can you show us the script used to run the contracts? I would like to replicate it...

Thanks

**Comment by zerjioang** [comment]
I removed the `--re-entrancy` flag and the expected results appeared. The analysis time also decreased to 17 minutes.

## Execution result:

```bash
KILLED: 0
ERRORED: 2
SUCCESS: 997
```


### killed list

* none

### errored list

* EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x0d8fc15b6fefc278ff642861df51b45607330871.evm

* EtherSolve_ICPC2021_ReplicationPackage/Benchmark/Bytecode-dataset-1000-contracts/Contract_0x424c9035bc3606f2887a5bbe28beaa9de49db9e8.evm

dataset-1000 took 17m24.554916292s

Any idea why the reentrancy detector triggers so many runtime errors when analyzing the dataset? Did you have the same problem when making your own tests? Any improvement ideas?

**Comment by VersusF** [comment]
Ok. Maybe it was not clear enough on the paper, the success rate was computed before the re-entrancy tests. This is however an interesting thing, thanks for reporting. Can i consider the issue resolved?

**Comment by zerjioang** [comment]
Sure! Thanks for the feedback
